name: CI-DT-Deploy

on:
  workflow_call:
    inputs:
      projectPackage:
        type: string
        description: Name of project package
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo ${{ inputs.projectPackage }}
